const TOTAL_ROUNDS = 5;
const MIN_DELAY = 1500;
const MAX_DELAY = 3500;

const CSS = `
:root{--bg:#050811;--panel:#09111e;--line:#18304a;--cyan:#00e5ff;--violet:#9b6cff;--orange:#ff7a18;--green:#39f5a1;--text:#eef7ff;--muted:#71849e}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}
html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow:hidden}
body{min-height:100dvh;touch-action:manipulation}
button{font:inherit}
.app{min-height:100dvh;display:flex;flex-direction:column;position:relative;overflow:hidden;background:radial-gradient(circle at 50% 18%,#07304a 0,transparent 34%),#050811}
.app:before{content:"";position:absolute;inset:0;pointer-events:none;opacity:.12;background-image:linear-gradient(#00e5ff 1px,transparent 1px),linear-gradient(90deg,#00e5ff 1px,transparent 1px);background-size:34px 34px;mask-image:linear-gradient(to bottom,#000,transparent 90%)}
.top{position:relative;z-index:2;display:flex;justify-content:space-between;align-items:center;padding:calc(12px + env(safe-area-inset-top)) 14px 10px;border-bottom:1px solid #17304a;background:#050811d9;backdrop-filter:blur(14px)}
.brand{display:flex;align-items:center;gap:10px}.boltMark{width:34px;height:34px;display:grid;place-items:center;border:1px solid #00e5ff66;border-radius:10px;background:#00e5ff0d;color:var(--cyan);font-size:20px;box-shadow:0 0 22px #00e5ff22}.brand strong{font-size:13px;letter-spacing:.05em}.brand span{display:block;color:var(--muted);font-size:9px;margin-top:2px;letter-spacing:.1em;text-transform:uppercase}
.exit{border:1px solid #20334e;background:#09111ee8;color:var(--muted);border-radius:10px;padding:8px 11px;font-size:10px;font-weight:900;letter-spacing:.08em}
.main{position:relative;z-index:1;flex:1;width:min(100%,520px);margin:auto;padding:12px 14px calc(14px + env(safe-area-inset-bottom));display:flex;flex-direction:column;gap:10px;min-height:0}
.hud{display:grid;grid-template-columns:1fr 1fr;gap:8px}.metric{border:1px solid var(--line);background:#09111ed9;border-radius:14px;padding:10px 12px;box-shadow:0 12px 28px #0006}.label{font-size:8px;color:var(--muted);font-weight:900;letter-spacing:.12em;text-transform:uppercase}.value{font-size:19px;font-weight:950;margin-top:4px}.cyan{color:var(--cyan)}
.rounds{display:flex;gap:5px;margin-top:7px}.dot{height:4px;flex:1;border-radius:99px;background:#172338}.dot.done{background:var(--green);box-shadow:0 0 9px #39f5a155}.dot.current{background:var(--cyan);box-shadow:0 0 10px #00e5ff88}
.game{position:relative;flex:1;min-height:270px;border:1px solid #18304a;border-radius:20px;background:#060d17cc;overflow:hidden;box-shadow:inset 0 0 60px #00e5ff06,0 18px 45px #0008}
.game:before{content:"";position:absolute;inset:0;pointer-events:none;background:radial-gradient(circle at 50% 50%,#00e5ff08,transparent 50%)}
.center{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;text-align:center;padding:24px}.eyebrow{font-size:9px;color:var(--cyan);font-weight:950;letter-spacing:.18em;text-transform:uppercase}.title{font-size:25px;font-weight:950;margin:9px 0}.copy{max-width:300px;color:var(--muted);font-size:12px;line-height:1.5;margin:0 auto}.pulse{width:72px;height:72px;border-radius:50%;border:1px solid #00e5ff55;background:#00e5ff0d;display:grid;place-items:center;margin:0 auto 15px;box-shadow:0 0 35px #00e5ff20;animation:pulse 1.6s infinite}.pulse b{font-size:30px;color:var(--cyan)}
.target{position:absolute;width:62px;height:62px;border-radius:50%;border:0;background:transparent;padding:0;transform:translate(-50%,-50%);cursor:pointer;z-index:3}.target .ring{position:absolute;inset:0;border:2px solid var(--cyan);border-radius:50%;box-shadow:0 0 16px #00e5ff99,inset 0 0 14px #00e5ff22;animation:targetPulse 1s infinite}.target .inner{position:absolute;inset:13px;border:1px solid #00e5ff99;border-radius:50%}.target .crossX,.target .crossY{position:absolute;background:var(--cyan);left:50%;top:50%;transform:translate(-50%,-50%);box-shadow:0 0 10px #00e5ff}.target .crossX{width:28px;height:2px}.target .crossY{width:2px;height:28px}.target .core{position:absolute;left:50%;top:50%;width:8px;height:8px;transform:translate(-50%,-50%);border-radius:50%;background:#fff;box-shadow:0 0 14px var(--cyan)}.target.fake .ring{border-color:var(--violet);box-shadow:0 0 16px #9b6cff99}.target.fake .inner{border-color:#9b6cff99}.target.fake .crossX,.target.fake .crossY{background:var(--violet);box-shadow:0 0 10px #9b6cff}.target.fake .core{box-shadow:0 0 14px var(--violet)}
.flash{position:absolute;inset:0;display:grid;place-items:center;background:#00e5ff08;animation:flash .35s}.flash b{font-size:76px;color:#fff;text-shadow:0 0 12px #fff,0 0 42px var(--cyan),0 0 90px var(--cyan)}
.feedback{min-height:20px;text-align:center;color:var(--muted);font-size:10px;font-weight:800}.good{color:var(--green)}.warn{color:#ffd166}.bad{color:#ff6b8a}
.cta{width:100%;border:1px solid #ff7a18aa;border-radius:14px;padding:14px;background:linear-gradient(135deg,#ff7a18,#ff9e2c);color:#07101a;font-size:13px;font-weight:950;letter-spacing:.08em;box-shadow:0 0 28px #ff7a1833}.cta:active{transform:scale(.985)}.cta.secondary{background:#09111e;border-color:#20334e;color:var(--text);box-shadow:none}.cta:disabled{background:#09111e;border-color:#20334e;color:#53677f;box-shadow:none}
.result{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:14px auto;width:min(100%,330px)}.result .metric{padding:12px}.big{font-size:27px;font-weight:950}.resultLabel{color:var(--muted);font-size:9px;margin-top:2px}.actions{display:flex;gap:8px;width:min(100%,330px);margin:0 auto}.actions .cta{flex:1}
@keyframes pulse{50%{transform:scale(1.06);box-shadow:0 0 50px #00e5ff35}}@keyframes targetPulse{50%{transform:scale(1.08)}}@keyframes flash{0%{opacity:.2;transform:scale(.92)}100%{opacity:1;transform:scale(1)}}
@media(max-height:620px){.game{min-height:220px}.top{padding-top:8px}.main{padding-top:8px}.title{font-size:21px}}
`;

export function renderLightningHtml(){return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>НейроГерой · Молния</title><style>${CSS}</style></head><body><div class="app" id="app"></div><script>
const TOTAL=${TOTAL_ROUNDS},MIN=${MIN_DELAY},MAX=${MAX_DELAY};
const app=document.getElementById('app');
const tg=()=>window.getTelegram?.()||window.Telegram?.WebApp||null;
let state='start',round=1,score=0,accuracy=100,totalClicks=0,correctClicks=0,reactions=[],current=0,targets=[],timer=0,startedAt=0,gameStartedAt=0,feedback='Нажми «Готов», когда будешь готов.',feedbackType='',locked=false,saved=false;
const avg=()=>Math.round(reactions.reduce((a,b)=>a+b,0)/reactions.length)||0;
const calcAccuracy=()=>totalClicks?Math.round(correctClicks/totalClicks*100):100;
function haptic(type){try{tg()?.HapticFeedback?.notificationOccurred(type)}catch(_) {}}
function back(){try{tg()?.BackButton?.hide()}catch(_){}location.assign('/')}
function clear(){clearTimeout(timer);timer=0}
function shell(inner){app.innerHTML='<header class="top"><div class="brand"><div class="boltMark">⚡</div><div><strong>НейроГерой</strong><span>Тренировка реакции</span></div></div><button class="exit" id="exit">ВЫХОД</button></header><main class="main">'+inner+'</main>';document.getElementById('exit').onclick=back}
function hud(){return '<section class="hud"><div class="metric"><div class="label">Последняя реакция</div><div class="value cyan">'+(current?current+' мс':'—')+'</div></div><div class="metric"><div class="label">Раунд</div><div class="value">'+round+' / '+TOTAL+'</div><div class="rounds">'+Array.from({length:TOTAL},(_,i)=>'<i class="dot '+(i<round-1?'done ':i===round-1?'current':'')+'"></i>').join('')+'</div></div></section>'}
function draw(){
 if(state==='start'){shell('<section class="game"><div class="center"><div><div class="pulse"><b>⚡</b></div><div class="eyebrow">МОЛНИЯ · СКОРОСТЬ РЕАКЦИИ</div><div class="title">Поймай вспышку</div><p class="copy">Жди сигнала. Как только появится цель — нажми на неё максимально быстро. В поздних раундах появятся ловушки.</p></div></div></section><div class="feedback">5 раундов · не торопись до сигнала</div><button class="cta" id="ready">ГОТОВ</button>');document.getElementById('ready').onclick=startRound;return}
 if(state==='game_over'){const a=calcAccuracy();const average=avg();shell('<section class="game"><div class="center"><div><div class="eyebrow">ТРЕНИРОВКА ЗАВЕРШЕНА</div><div class="title">⚡ '+score+' очков</div><p class="copy">Пять раундов пройдены. Твой средний отклик — '+average+' мс.</p><div class="result"><div class="metric"><div class="big cyan">'+average+' мс</div><div class="resultLabel">средняя реакция</div></div><div class="metric"><div class="big">'+a+'%</div><div class="resultLabel">точность</div></div><div class="metric"><div class="big">'+correctClicks+'/'+totalClicks+'</div><div class="resultLabel">точные нажатия</div></div><div class="metric"><div class="big">'+score+'</div><div class="resultLabel">счёт</div></div></div></div></div></section><div class="actions"><button class="cta secondary" id="again">ЕЩЁ РАЗ</button><button class="cta" id="menu">В МЕНЮ</button></div>');document.getElementById('again').onclick=restart;document.getElementById('menu').onclick=back;save();return}
 shell(hud()+'<section class="game" id="game"></section><div class="feedback '+feedbackType+'">'+feedback+'</div>'+actionButton());
 bindGame();
}
function actionButton(){if(state==='countdown'||state==='waiting_for_stimulus')return '<button class="cta" disabled>ЖДИ СИГНАЛА…</button>';if(state==='stimulus_active')return '<button class="cta" disabled>ТАПАЙ ПО ЦЕЛЯМ</button>';if(state==='round_summary')return '<button class="cta" id="next">СЛЕДУЮЩИЙ РАУНД</button>';return '<button class="cta" disabled>…</button>'}
function bindGame(){const game=document.getElementById('game');if(!game)return;if(state==='countdown'){game.innerHTML='<div class="center"><div><div class="eyebrow">РАУНД '+round+'</div><div class="title">Приготовься</div><p class="copy">Сейчас будет пауза. Не нажимай.</p></div></div>';return}if(state==='waiting_for_stimulus'){game.onpointerdown=()=>{if(locked)return;totalClicks++;accuracy=calcAccuracy();feedback='Рано! Дождись вспышки.';feedbackType='warn';haptic('error');draw()};return}if(state==='stimulus_active'){game.innerHTML=targets.map(t=>'<button class="target '+(t.isFake?'fake':'')+'" data-id="'+t.id+'" style="left:'+t.x+'px;top:'+t.y+'px" aria-label="цель"><i class="ring"></i><i class="inner"></i><i class="crossX"></i><i class="crossY"></i><i class="core"></i></button>').join('');game.onpointerdown=(e)=>{if(e.target.closest('.target'))return;totalClicks++;accuracy=calcAccuracy();feedback='Мимо! Будь внимательнее.';feedbackType='bad';draw()};game.querySelectorAll('.target').forEach(b=>b.addEventListener('pointerdown',e=>hit(Number(b.dataset.id),e)));return}if(state==='round_summary'){document.getElementById('next').onclick=nextRound}}
function startRound(){round=1;score=0;accuracy=100;totalClicks=0;correctClicks=0;reactions=[];current=0;saved=false;gameStartedAt=performance.now();startCountdown()}
function startCountdown(){clear();locked=false;state='countdown';feedback='Приготовься…';feedbackType='';draw();timer=setTimeout(spawn,MIN+Math.random()*(MAX-MIN))}
function spawn(){if(state!=='countdown')return;state='waiting_for_stimulus';feedback='Жди вспышку';feedbackType='';draw();timer=setTimeout(()=>{if(state!=='waiting_for_stimulus'||locked)return;spawnTargets()},0)}
function spawnTargets(){const game=document.getElementById('game');if(!game)return;const r=game.getBoundingClientRect();const count=round<=2?1:round<=4?2:3;targets=[];for(let i=0;i<count;i++){const margin=42;targets.push({id:i,x:margin+Math.random()*Math.max(1,r.width-margin*2),y:margin+Math.random()*Math.max(1,r.height-margin*2),clicked:false,isFake:round>2&&Math.random()<.15})}state='stimulus_active';startedAt=performance.now();feedback='ТАПАЙ!';feedbackType='cyan';haptic('warning');draw()}
function hit(id,e){e.preventDefault();e.stopPropagation();if(state!=='stimulus_active'||locked)return;const t=targets.find(x=>x.id===id);if(!t||t.clicked)return;totalClicks++;if(t.isFake){t.clicked=true;accuracy=calcAccuracy();feedback='Ой! Это ловушка.';feedbackType='bad';haptic('error');draw();return}const elapsed=Math.max(1,Math.round(performance.now()-startedAt));t.clicked=true;correctClicks++;current=elapsed;reactions=reactions.concat(elapsed);const remaining=targets.filter(x=>!x.isFake&&!x.clicked);if(remaining.length){feedback='Есть! Ещё цель';feedbackType='good';draw();return}const bonus=Math.max(10,Math.round((1000-elapsed)/5));score+=200+bonus;accuracy=calcAccuracy();feedback=elapsed<250?'Молния! Невероятная скорость! ⚡':elapsed<400?'Очень быстро! Так держать!':'Хорошая реакция!';feedbackType='good';locked=true;state='round_summary';haptic('success');draw()}
function nextRound(){if(round<TOTAL){round++;startCountdown()}else{state='game_over';draw()}}
function restart(){clear();state='start';round=1;score=0;accuracy=100;totalClicks=0;correctClicks=0;reactions=[];current=0;targets=[];feedback='Нажми «Готов», когда будешь готов.';feedbackType='';saved=false;draw()}
async function save(){if(saved)return;saved=true;const initData=tg()?.initData;if(!initData)return;try{const r=await fetch('/api/game-sessions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({initData,game_code:'lightning',score,difficulty:1,reaction_ms:avg()||null,false_starts:0,accuracy_percent:calcAccuracy(),duration_ms:Math.max(1,Math.round(performance.now()-gameStartedAt)),error_count:Math.max(0,totalClicks-correctClicks),input_timing_ms:reactions,metadata:{rounds:TOTAL,complete:true,source:'ReactionGame.jsx'}})});if(!r.ok)throw new Error('save')}catch(_){saved=false}}
try{tg()?.ready();tg()?.expand();tg()?.BackButton?.show();tg()?.BackButton?.onClick(back)}catch(_){}draw();
</script></body></html>`}
