import app from "./progress_entry.js";
import { renderProgressPage } from "./progress_page.js";

const MAX_AUTH_AGE_SECONDS=3600;

export default {async fetch(request,env,ctx){const url=new URL(request.url);if(request.method==="GET"&&url.pathname==="/api/progression")return progressionApi(request,env);if(request.method==="GET"&&url.pathname==="/progress")return renderProgressPage();return app.fetch(request,env,ctx)}};

async function progressionApi(request,env){const auth=await validateTelegramInitData(request.headers.get("x-telegram-init-data"),env.TELEGRAM_BOT_TOKEN);if(!auth.ok)return json({ok:false,error:auth.error},401);const key=env.SUPABASE_SECRET_KEY;if(!env.SUPABASE_URL||!key)return json({ok:false,error:"Server storage configuration error"},500);const base=env.SUPABASE_URL.replace(/\/$/,"")+"/rest/v1/",headers={apikey:key,Authorization:"Bearer "+key};try{const player=await getOne(base+"players?select=id&telegram_id=eq."+encodeURIComponent(auth.user.id)+"&limit=1",headers);if(!player)return json({ok:true,achievements:[],quests:[]});const sessions=await getRows(base+"game_sessions?select=game_code,score,accuracy_percent,completed_at,created_at&player_id=eq."+encodeURIComponent(player.id)+"&order=created_at.desc&limit=2000",headers);const now=new Date(),today=now.toISOString().slice(0,10),todayRows=sessions.filter(s=>String(s.created_at||s.completed_at||"").slice(0,10)===today),scores=todayRows.map(s=>Number(s.score)).filter(Number.isFinite),accuracies=todayRows.map(s=>Number(s.accuracy_percent)).filter(Number.isFinite),games=new Set(sessions.map(s=>s.game_code));const total=sessions.length,highAccuracy=accuracies.some(x=>x>=90),sumToday=scores.reduce((a,b)=>a+b,0),achievements=[{id:"first_step",title:"Первый шаг",text:"Сыграй первую тренировку",done:total>=1,progress:Math.min(total,1),goal:1},{id:"warmup",title:"Разминка",text:"Сыграй 3 тренировки",done:total>=3,progress:Math.min(total,3),goal:3},{id:"accuracy",title:"Точный прицел",text:"Получи точность 90%+",done:highAccuracy,progress:highAccuracy?1:0,goal:1},{id:"master",title:"Мастер тренировок",text:"Сыграй 10 тренировок",done:total>=10,progress:Math.min(total,10),goal:10},{id:"explorer",title:"Исследователь",text:"Попробуй 4 разные игры",done:games.size>=4,progress:Math.min(games.size,4),goal:4}],quests=[{id:"play2",title:"Две тренировки",text:"Сыграй 2 раза сегодня",progress:Math.min(todayRows.length,2),goal:2,reward:20},{id:"score500",title:"Набор очков",text:"Набери 500 очков сегодня",progress:Math.min(Math.round(sumToday),500),goal:500,reward:30},{id:"accuracy80",title:"Чистая серия",text:"Заверши 2 тренировки с точностью 80%+",progress:Math.min(todayRows.filter(s=>Number(s.accuracy_percent)>=80).length,2),goal:2,reward:30}];return json({ok:true,achievements,quests,date:today})}catch(_){return json({ok:false,error:"Could not load progression"},502)}}
async function getRows(url,headers){const r=await fetch(url,{headers});if(!r.ok)throw new Error("query");const v=await r.json();return Array.isArray(v)?v:[]}
async function getOne(url,headers){const v=await getRows(url,headers);return v[0]||null}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=UTF-8","cache-control":"no-store"}})}
async function validateTelegramInitData(initData,botToken){if(!initData||!botToken)return{ok:false,error:"Missing Telegram authorization"};const p=new URLSearchParams(initData),hash=p.get("hash"),date=Number(p.get("auth_date")),raw=p.get("user");if(!hash||!date||!raw)return{ok:false,error:"Invalid Telegram initData"};const now=Math.floor(Date.now()/1000);if(date>now+60||now-date>MAX_AUTH_AGE_SECONDS)return{ok:false,error:"Telegram authorization expired"};p.delete("hash");const s=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+"="+v).join("\n"),e=new TextEncoder(),secret=await hmac(e.encode("WebAppData"),e.encode(botToken)),calc=toHex(await hmac(secret,e.encode(s)));if(calc.length!==hash.length||!constantTimeEqual(calc,hash))return{ok:false,error:"Invalid Telegram signature"};let u;try{u=JSON.parse(raw)}catch{return{ok:false,error:"Invalid Telegram user"}}return u?.id?{ok:true,user:{id:u.id,first_name:u.first_name??null,username:u.username??null}}:{ok:false,error:"Telegram user not found"}}
async function hmac(key,data){const k=await crypto.subtle.importKey("raw",key,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return crypto.subtle.sign("HMAC",k,data)}function toHex(b){return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}function constantTimeEqual(a,b){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}